### ISSUE TITLE
Spawning domains in split panes

### ISSUE THREAD

**Issue by MLFlexer** [DavidRR-F/quick_domains.wezterm#1]
Awesome plugin! 
It would be even better if it was possible to split panes and attach a domain to the newly split pane. 

Adding 2 new keybinds, one for vertical and one for horizontal splits would be one way to approach it.

another way would be to have 2 elements per domain, one for vertical and another for horizontal, then distinguish each with a nerd font or color

I think I would prefer the 2 keybinds

**Comment by DavidRR-F** [comment]
Thats a good Idea! I had actually thought about adding a action option to define either splitting or opening a new tab, but adding the extra binds would provide more granularity

**Comment by MLFlexer** [comment]
I personally would really appreciate keybindings for splits, if you need help with the PR, then let me know :smile:

**Comment by DavidRR-F** [comment]
Yah I like the idea as well and I am working on the extra keys. The only issue I have come across is with adding these is that wezterm does not support splitting with remote domains using the default actions, and the MuxDomain object does not have a class function to grab the remote host information (remote address, identity file, etc..) to use SpawnCommand without wezterm connect. So I will most likely filter out remote domains from the split list until I can find an alternative
