### ISSUE TITLE
Emit show and hide events

### ISSUE THREAD

**Issue by michaelbrusegard** [DavidRR-F/quick_domains.wezterm#2]
Would it be possible to emit show and hide events for when the fuzzy finder opens/closes? This way I can make an extension for [tabline.wez](https://github.com/michaelbrusegard/tabline.wez) that shows a different tabline when the fuzzyfinder is open/closed.

**Comment by DavidRR-F** [comment]
That should be easy enough to add. I have not used [tabline.wez](https://github.com/michaelbrusegard/tabline.wez) What does it need to trigger just a generic emit("domain_menu_open") and emit("domain_menu_closed") on select or cancel?

**Comment by michaelbrusegard** [comment]
Yes just a generic open and close event. Preferably you would also emit the window object if possible, because that way it can update the tab bar instantly instead of relying on the update-status interval

**Comment by DavidRR-F** [comment]
So something along the lines of:

```lua
local function fuzzy_attach_to_domain(opts, action)
  return wezterm.action_callback(function(window, pane)
    local choices = get_domains(opts)
    
    -- Emit window opened
    wezterm.emit('quick_domain.fuzzy_selector.opened', window)

    window:perform_action(
      act.InputSelector({
        action = wezterm.action_callback(function(window, pane, id, label)
          if id then

            -- Perform the selected action
            window:perform_action(
              get_action(id, action),
              pane
            )
            -- Emit action selected
            wezterm.emit('quick_domain.fuzzy_selector.selected', window)

          else

            -- Emit action cancelled
            wezterm.emit('quick_domain.fuzzy_selector.canceled', window)

          end
        end),
        title = "Choose Domain",
        description = "Select a host and press Enter = accept, Esc = cancel, / = filter",
        fuzzy_description = opts.icons.hosts .. " " .. "Domains: ",
        choices = choices,
        fuzzy = true,
      }),
      pane
    )
  end)
end

```
