### ISSUE TITLE
Styling the fuzzy picker

### ISSUE THREAD

**Issue by joncrangle** [DavidRR-F/quick_domains.wezterm#3]
Thanks for creating this plugin!

Could you expose an option to let the user style the fuzzy picker by providing a `wezterm.format` function?

`smart_workspace_switcher.wezterm` [does it here](https://github.com/MLFlexer/smart_workspace_switcher.wezterm/blob/main/plugin/init.lua#L22) and it would be a nice-to-have.

**Comment by DavidRR-F** [comment]
Yah sure, I will look over the docs for that.

**Comment by joncrangle** [comment]
Thank you! It works great.
